#ifndef OCTREE_COMMON_H
#define OCTREE_COMMON_H

#define OCTREE_BINDING_COUNTER 0
#define OCTREE_BINDING_OCTREE 1
#define OCTREE_BINDING_OCTREE_DATA 2
#define OCTREE_BINDING_OCTREE_MIPMAP_DATA 3
#define OCTREE_BINDING_FRAGMENTLIST 4
#define OCTREE_BINDING_BUILDINFO 5
#define OCTREE_BINDING_INDIRECT 6
#define OCTREE_BINDING_OBJECT 7
#define OCTREE_BINDING_CAMERA 8

#define OCTREE_GROUP_SIZE 64

#define OCTREE_COLOR_INDEX 0
#define OCTREE_NORMAL_INDEX 1
#define OCTREE_EMISSIVE_INDEX 2
#define OCTREE_RADIANCE_INDEX 3

#endif