#ifndef OCTREE_COMMON_H
#define OCTREE_COMMON_H

#define OCTREE_BINDING_COUNTER 0
#define OCTREE_BINDING_OCTTREE 1
#define OCTREE_BINDING_FRAGMENTLIST 2
#define OCTREE_BINDING_BUILDINFO 3
#define OCTREE_BINDING_INDIRECT 4
#define OCTREE_BINDING_OBJECT 5

#define GROUP_SIZE 64

#endif