#include "octree_common.h"
layout(local_size_x = OCTREE_GROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

layout(binding = OCTREE_BINDING_OCTREE) buffer uuOctree { uvec4 uOctree[]; };
layout(binding = OCTREE_BINDING_BUILDINFO) readonly buffer uuBuildInfo { uint uAllocBegin, uAllocNum; };

void main()
{
	if (gl_GlobalInvocationID.x >= uAllocNum)
		return;
	uOctree[gl_GlobalInvocationID.x + uAllocBegin] = uvec4(0);
}