#include "KVertexDefinition.h"
#include <algorithm>

namespace KVertexDefinition
{
	static VertexDetail POS_3F_NORM_3F_UV_2F_DETAILS;
	static VertexDetail UV2_2F_DETAILS;
	static VertexDetail DIFF_3F_SPEC_3F_DETAILS;
	static VertexDetail TAN_3F_BIN_3F_DETAILS;
	static VertexDetail BW_4F_BI_4I_DETAILS;
	static VertexDetail GUI_POS_2F_UV_2F_COLOR_4BYTE_DETAILS;
	static VertexDetail SCREENQUAD_POS_2F_DETAILS;
	static VertexDetail DEBUG_POS_3F_DETAILS;
	static VertexDetail INSTANCE_DATA_DETAILS;
	static VertexDetail TERRAIN_DATA_DETAILS;
	static VertexDetail EMPYT_DETAILS;

	static bool VERTEX_DETAIL_INIT = false;

	void StaticInit()
	{
		if (!VERTEX_DETAIL_INIT)
		{
			// POS_3F_NORM_3F_UV_2F
			{
				POS_3F_NORM_3F_UV_2F_DETAILS.semanticDetails.push_back({ VS_POSITION, EF_R32G32B32_FLOAT, MEMBER_OFFSET(POS_3F_NORM_3F_UV_2F, POSITION) });
				POS_3F_NORM_3F_UV_2F_DETAILS.semanticDetails.push_back({ VS_NORMAL, EF_R32G32B32_FLOAT, MEMBER_OFFSET(POS_3F_NORM_3F_UV_2F, NORMAL) });
				POS_3F_NORM_3F_UV_2F_DETAILS.semanticDetails.push_back({ VS_TEXCOORD0, EF_R32G32_FLOAT, MEMBER_OFFSET(POS_3F_NORM_3F_UV_2F, UV) });
				POS_3F_NORM_3F_UV_2F_DETAILS.vertexSize = sizeof(POS_3F_NORM_3F_UV_2F);
			}
			// UV2_2F
			{
				UV2_2F_DETAILS.semanticDetails.push_back({ VS_TEXCOORD1, EF_R32G32_FLOAT, MEMBER_OFFSET(UV2_2F, UV2) });
				UV2_2F_DETAILS.vertexSize = sizeof(UV2_2F);
			}
			// DIFF_2F_SPEC_2F
			{
				DIFF_3F_SPEC_3F_DETAILS.semanticDetails.push_back({ VS_DIFFUSE, EF_R32G32B32_FLOAT, MEMBER_OFFSET(DIFF_3F_SPEC_3F, DIFFUSE) });
				DIFF_3F_SPEC_3F_DETAILS.semanticDetails.push_back({ VS_SPECULAR, EF_R32G32B32_FLOAT, MEMBER_OFFSET(DIFF_3F_SPEC_3F, SPECULAR) });
				DIFF_3F_SPEC_3F_DETAILS.vertexSize = sizeof(DIFF_3F_SPEC_3F);
			}
			// TAN_3F_BIN_3F
			{
				TAN_3F_BIN_3F_DETAILS.semanticDetails.push_back({ VS_TANGENT, EF_R32G32B32_FLOAT, MEMBER_OFFSET(TAN_3F_BIN_3F, TANGENT) });
				TAN_3F_BIN_3F_DETAILS.semanticDetails.push_back({ VS_BINORMAL, EF_R32G32B32_FLOAT, MEMBER_OFFSET(TAN_3F_BIN_3F, BINORMAL) });
				TAN_3F_BIN_3F_DETAILS.vertexSize = sizeof(TAN_3F_BIN_3F);
			}
			// BW_4F_BI_4I
			{
				BW_4F_BI_4I_DETAILS.semanticDetails.push_back({ VS_BLEND_WEIGHTS, EF_R32_FLOAT, MEMBER_OFFSET(BW_4F_BI_4I, BLEND_WEIGHTS) });
				BW_4F_BI_4I_DETAILS.semanticDetails.push_back({ VS_BLEND_INDICES, EF_R32_UINT, MEMBER_OFFSET(BW_4F_BI_4I, BLEND_INDICES) });
				BW_4F_BI_4I_DETAILS.vertexSize = sizeof(BW_4F_BI_4I);
			}
			// GUI_POS_2F_UV_2F_COLOR_4BYTE_DETAILS
			{
				GUI_POS_2F_UV_2F_COLOR_4BYTE_DETAILS.semanticDetails.push_back({ VS_GUI_POS, EF_R32G32_FLOAT, MEMBER_OFFSET(GUI_POS_2F_UV_2F_COLOR_4BYTE, GUI_POSITION) });
				GUI_POS_2F_UV_2F_COLOR_4BYTE_DETAILS.semanticDetails.push_back({ VS_GUI_UV, EF_R32G32_FLOAT, MEMBER_OFFSET(GUI_POS_2F_UV_2F_COLOR_4BYTE, GUI_UV) });
				GUI_POS_2F_UV_2F_COLOR_4BYTE_DETAILS.semanticDetails.push_back({ VS_GUI_COLOR, EF_R8G8B8A8_UNORM, MEMBER_OFFSET(GUI_POS_2F_UV_2F_COLOR_4BYTE, GUI_COLOR) });
				GUI_POS_2F_UV_2F_COLOR_4BYTE_DETAILS.vertexSize = sizeof(GUI_POS_2F_UV_2F_COLOR_4BYTE);
			}
			// SCREENQUAD_POS_2F_DETAILS
			{
				SCREENQUAD_POS_2F_DETAILS.semanticDetails.push_back({ VS_SCREENQAUD_POS, EF_R32G32_FLOAT, MEMBER_OFFSET(SCREENQUAD_POS_2F, QUAD_POSITION) });
				SCREENQUAD_POS_2F_DETAILS.vertexSize = sizeof(SCREENQUAD_POS_2F);
			}
			// DEBUG_POS_3F_DETAILS
			{
				DEBUG_POS_3F_DETAILS.semanticDetails.push_back({ VS_POSITION, EF_R32G32B32_FLOAT, MEMBER_OFFSET(DEBUG_POS_3F, DEBUG_POSITION) });
				DEBUG_POS_3F_DETAILS.vertexSize = sizeof(DEBUG_POS_3F);
			}
			// INSTANCE_DATA_DETAILS
			{
				INSTANCE_DATA_DETAILS.semanticDetails.push_back({ VS_INSTANCE_ROW_0, EF_R32G32B32A32_FLOAT, MEMBER_OFFSET(INSTANCE_DATA_MATRIX4F, ROW0) });
				INSTANCE_DATA_DETAILS.semanticDetails.push_back({ VS_INSTANCE_ROW_1, EF_R32G32B32A32_FLOAT, MEMBER_OFFSET(INSTANCE_DATA_MATRIX4F, ROW1) });
				INSTANCE_DATA_DETAILS.semanticDetails.push_back({ VS_INSTANCE_ROW_2, EF_R32G32B32A32_FLOAT, MEMBER_OFFSET(INSTANCE_DATA_MATRIX4F, ROW2) });
				INSTANCE_DATA_DETAILS.semanticDetails.push_back({ VS_INSTANCE_PREV_ROW_0, EF_R32G32B32A32_FLOAT, MEMBER_OFFSET(INSTANCE_DATA_MATRIX4F, PREV_ROW0) });
				INSTANCE_DATA_DETAILS.semanticDetails.push_back({ VS_INSTANCE_PREV_ROW_1, EF_R32G32B32A32_FLOAT, MEMBER_OFFSET(INSTANCE_DATA_MATRIX4F, PREV_ROW1) });
				INSTANCE_DATA_DETAILS.semanticDetails.push_back({ VS_INSTANCE_PREV_ROW_2, EF_R32G32B32A32_FLOAT, MEMBER_OFFSET(INSTANCE_DATA_MATRIX4F, PREV_ROW2) });
				INSTANCE_DATA_DETAILS.vertexSize = sizeof(INSTANCE_DATA_MATRIX4F);
			}
			// TERRAIN_DATA_DETAILS
			{
				TERRAIN_DATA_DETAILS.semanticDetails.push_back({ VS_TERRAIN_POS, EF_R32G32_FLOAT, MEMBER_OFFSET(TERRAIN_POS_2F, POS) });
				TERRAIN_DATA_DETAILS.vertexSize = sizeof(TERRAIN_POS_2F);
			}
			VERTEX_DETAIL_INIT = true;
		}
	}

	const VertexDetail& GetVertexDetail(VertexFormat format)
	{
		StaticInit();
		switch (format)
		{
		case VF_POINT_NORMAL_UV:
			return POS_3F_NORM_3F_UV_2F_DETAILS;
		case VF_UV2:
			return UV2_2F_DETAILS;
		case VF_DIFFUSE_SPECULAR:
			return DIFF_3F_SPEC_3F_DETAILS;
		case VF_TANGENT_BINORMAL:
			return TAN_3F_BIN_3F_DETAILS;
		case VF_BLEND_WEIGHTS_INDICES:
			return BW_4F_BI_4I_DETAILS;
		case VF_GUI_POS_UV_COLOR:
			return GUI_POS_2F_UV_2F_COLOR_4BYTE_DETAILS;
		case VF_SCREENQUAD_POS:
			return SCREENQUAD_POS_2F_DETAILS;
		case VF_DEBUG_POINT:
			return DEBUG_POS_3F_DETAILS;
		case VF_INSTANCE:
			return INSTANCE_DATA_DETAILS;
		case VF_TERRAIN_POS:
			return TERRAIN_DATA_DETAILS;
		default:
			assert(false && "unknown format");
			return EMPYT_DETAILS;
		}
	}
}