#ifndef _CLIP_PUBLIC_H_
#define _CLIP_PUBLIC_H_

#define BINDING_IMAGE_IN BINDING_TEXTURE9
#define BINDING_IMAGE_OUT BINDING_TEXTURE10
#define UPDATE_GROUP_SIZE 16
#define ENABLE_CLIP_DEBUG

#endif