--- #YAML:1.0
name:                DB_File
version:             1.817
abstract:            Perl5 access to Berkeley DB version 1.x
license:             perl
author:              
    - Paul Marquess <pmqs@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
