#ifndef ABUFFER_PUBLIC_H
#define ABUFFER_PUBLIC_H

#define GROUP_SIZE 32

#define ABUFFER_BINDING_LINK_HEADER 0
#define ABUFFER_BINDING_LINK_NEXT 1
#define ABUFFER_BINDING_LINK_DEPTH 2
#define ABUFFER_BINDING_LINK_RESULT 3
#define ABUFFER_BINDING_OBJECT 4

#endif