#include "abuffer_public.h"

layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE) in;
layout(binding = ABUFFER_BINDING_LINK_HEADER, r32ui) uniform uimage2D LinkHeader;

layout(binding = ABUFFER_BINDING_OBJECT)
uniform Object_DYN_UNIFORM
{
	// width height maxElements
	uvec4 miscs;
} object;

void main()
{
	uvec2 coord = gl_GlobalInvocationID.xy;
	if (all(lessThan(ivec2(coord), ivec2(object.miscs.xy))))
	{
		imageStore(LinkHeader, ivec2(coord), uvec4(uint(-1)));
	}
}