#include "vg_define.h"

layout(local_size_x = VG_GROUP_SIZE, local_size_y = 1, local_size_z = 1) in;
void main()
{
	uint globalIndex = gl_GlobalInvocationID.x;
	if (globalIndex == 0)
	{
		IndirectArgs[0] = (QueueState[QUEUE_STATE_INDEX].visibleClusterNum + VG_GROUP_SIZE - 1) / VG_GROUP_SIZE;
		IndirectArgs[1] = 1;
		IndirectArgs[2] = 1;
	}
	if (globalIndex < numBinning)
	{
		BinningHeader[globalIndex] = uvec4(0, 0, 0, 0);
	}
}