#ifndef VG_BASEPASS_BINDING_H
#define VG_BASEPASS_BINDING_H

#define BINDING_GLOBAL_DATA 16
#define BINDING_RESOURCE 17
#define BINDING_QUEUE_STATE 18
#define BINDING_INSTANCE_DATA 19
#define BINDING_HIERARCHY 20
#define BINDING_CLUSTER_BATCH 21
#define BINDING_CLUSTER_STORAGE_VERTEX 22
#define BINDING_CLUSTER_STORAGE_INDEX 23
#define BINDING_CANDIDATE_NODE_BATCH 24
#define BINDING_CANDIDATE_CLUSTER_BATCH 25
#define BINDING_SELECTED_CLUSTER_BATCH 26
#define BINDING_INDIRECT_ARGS 27
#define BINDING_EXTRA_DEBUG_INFO 28
#define BINDING_INDIRECT_DRAW_ARGS 29
#define BINDING_CLUSTER_VERTEX_BUFFER 30
#define BINDING_CLUSTER_INDEX_BUFFER 31
#define BINDING_BINNING_DATA 32
#define BINDING_BINNING_HEADER 33
#define BINDING_MATEIRAL_DATA 34

#endif