#ifndef VG_DEFAULT_BINGINNG_H
#define VG_DEFAULT_BINGINNG_H

// Match with KVirtualGeometryScene
#define BINDING_GLOBAL_DATA 0
#define BINDING_RESOURCE 1
#define BINDING_QUEUE_STATE 2
#define BINDING_INSTANCE_DATA 3
#define BINDING_HIERARCHY 4
#define BINDING_CLUSTER_BATCH 5
#define BINDING_CLUSTER_STORAGE_VERTEX 6
#define BINDING_CLUSTER_STORAGE_INDEX 7
#define BINDING_CANDIDATE_NODE_BATCH 8
#define BINDING_CANDIDATE_CLUSTER_BATCH 9
#define BINDING_SELECTED_CLUSTER_BATCH 10
#define BINDING_INDIRECT_ARGS 11
#define BINDING_EXTRA_DEBUG_INFO 12
#define BINDING_INDIRECT_DRAW_ARGS 13
#define BINDING_INDIRECT_MESH_ARGS 14
#define BINDING_CLUSTER_VERTEX_BUFFER 15
#define BINDING_CLUSTER_INDEX_BUFFER 16
#define BINDING_CLUSTER_MATERIAL_BUFFER 17
#define BINDING_BINNING_DATA 18
#define BINDING_BINNING_HEADER 19
#define BINDING_MATEIRAL_DATA 20
#define BINDING_HIZ_BUFFER 21
#define BINDING_MAIN_CULL_RESULT 22
#define BINDING_POST_CULL_INDIRECT_ARGS 23

#endif