#ifndef _RTAO_DEFINE_H_
#define _RTAO_DEFINE_H_

#define BINDING_GBUFFER_NORMAL 0
#define BINDING_GBUFFER_POSITION 1
#define BINDING_VELOCITY 2
#define BINDING_AS 3
#define BDINING_UNIFORM 4
#define BINDING_MEAN_VARIANCE_INPUT 5
#define BINDING_MEAN_VARIANCE_OUTPUT 6
#define BINDING_PREV 7
#define BINDING_FINAL 8
#define BINDING_CUR 9

#endif